name: Check PR can be merged
on:
  pull_request:
    types: [labeled]
    branches:
      - main/* # The branch you want to automatically merge pull request
jobs:
  merge_action:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically Merge PR
        uses: plm9606/automerge_actions@1.2.2
        with:
          # The label name to automatically merge. Default is "automerge".
          label-name: automerge
          # GitHub WebHook Secret Token
          github-token: ${{ secrets.GITHUB_TOKEN }}