name: workflow-for-testing
on:
  pull_request:
    types: [opened]

jobs:
  automerging_pool_requests:
    runs-on: ubuntu-20.04
    steps:
      - name: print
        shell: bash
        run: |
          echo 'Hello world! ' ${{ github.actor }}

